server:
  port: 8080

spring:
  application:
    name: appointment-service
  mvc:
    log-request-details: true
  cloud:
    consul:
      host: ${consul.host:localhost}
      port: ${consul.port:8500}
    loadbalancer:
      ribbon:
        enabled: false
  flyway:
    url: jdbc:postgresql://${postgres.host:localhost}:5432/${postgres.db:test}?currentSchema=demo
    user: ${postgres.user:kmandalas}
    password: ${postgres.password:passepartout}
  #    schemas: demo
  #    locations: db/migration
  r2dbc:
    url: r2dbc:postgresql://${postgres.host:localhost}:5432/${postgres.db:test}?currentSchema=demo
    username: ${postgres.user:kmandalas}
    password: ${postgres.password:passepartout}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    gr.kmandalas: DEBUG
    org.springframework.web: TRACE

external:
  services:
    notifications: ${notification.service.host:localhost}:${notification.service.port:8005}/notifications
    number-information: ${number-information.service.host:localhost}:${number-information.service.port:8005}/number-information